### ISSUE TITLE
fails to build on fedora 35

### ISSUE THREAD

**Issue by erentar** [sagemath/cysignals#160] opened 2021-12-02 08:30 UTC
cysignals spkg fails to build while building sagemath, ive opened a subshell as sage instructed me to find this:
```
(sage-buildsh) user@root:cysignals-1.10.3$ pip install ./src/
Processing ./src
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
Requirement already satisfied: Cython>=0.28 in /home/user/git/sage/local/lib/python3.9/site-packages (from cysignals==1.10.3) (0.29.24)
Building wheels for collected packages: cysignals
  Building wheel for cysignals (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/user/git/sage/local/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-b42k_wkp/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-b42k_wkp/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-wtb68z34
       cwd: /tmp/pip-req-build-b42k_wkp/
  Complete output (33 lines):
  running bdist_wheel
  running build
  running build_py
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/cysignals
  copying src/cysignals/__init__.py -> build/lib.linux-x86_64-3.9/cysignals
  copying src/cysignals/memory.pxi -> build/lib.linux-x86_64-3.9/cysignals
  copying src/cysignals/signals.pxi -> build/lib.linux-x86_64-3.9/cysignals
  copying src/cysignals/signals.pxd -> build/lib.linux-x86_64-3.9/cysignals
  copying src/cysignals/pysignals.pxd -> build/lib.linux-x86_64-3.9/cysignals
  copying src/cysignals/memory.pxd -> build/lib.linux-x86_64-3.9/cysignals
  copying src/cysignals/cysignals_config.h -> build/lib.linux-x86_64-3.9/cysignals
  copying src/cysignals/pxi_warning.h -> build/lib.linux-x86_64-3.9/cysignals
  copying src/cysignals/macros.h -> build/lib.linux-x86_64-3.9/cysignals
  copying src/cysignals/struct_signals.h -> build/lib.linux-x86_64-3.9/cysignals
  running build_ext
  building 'cysignals.signals' extension
  creating build/temp.linux-x86_64-3.9
  creating build/temp.linux-x86_64-3.9/build
  creating build/temp.linux-x86_64-3.9/build/src
  creating build/temp.linux-x86_64-3.9/build/src/cysignals
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wno-unused -g -O2 -g -O2 -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -U_FORTIFY_SOURCE -Isrc/cysignals -Isrc -I/home/user/git/sage/local/include/python3.9 -c build/src/cysignals/signals.c -o build/temp.linux-x86_64-3.9/build/src/cysignals/signals.o -pthread
  In file included from build/src/cysignals/signals.c:1585:
  build/src/cysignals/implementation.c: In function ‘setup_trampoline’:
  build/src/cysignals/implementation.c:339:29: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘long int’ [-Wsign-compare]
    339 |     if (trampolinestacksize < PTHREAD_STACK_MIN)
        |                             ^
  In file included from build/src/cysignals/signals.c:1585:
  build/src/cysignals/implementation.c: In function ‘setup_alt_stack’:
  build/src/cysignals/implementation.c:448:17: error: storage size of ‘alt_stack’ isn’t constant
    448 |     static char alt_stack[MINSIGSTKSZ + 5120 + BACKTRACELEN * sizeof(void*)];
        |                 ^~~~~~~~~
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for cysignals
  Running setup.py clean for cysignals
Failed to build cysignals
Installing collected packages: cysignals
  Attempting uninstall: cysignals
    Found existing installation: cysignals 1.11.1
    Uninstalling cysignals-1.11.1:
      Successfully uninstalled cysignals-1.11.1
    Running setup.py install for cysignals ... error
    ERROR: Command errored out with exit status 1:
     command: /home/user/git/sage/local/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-b42k_wkp/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-b42k_wkp/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-m6wbav70/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/git/sage/local/include/python3.9/cysignals
         cwd: /tmp/pip-req-build-b42k_wkp/
    Complete output (33 lines):
    running install
    running build
    running build_py
    creating build/lib.linux-x86_64-3.9
    creating build/lib.linux-x86_64-3.9/cysignals
    copying src/cysignals/__init__.py -> build/lib.linux-x86_64-3.9/cysignals
    copying src/cysignals/memory.pxi -> build/lib.linux-x86_64-3.9/cysignals
    copying src/cysignals/signals.pxi -> build/lib.linux-x86_64-3.9/cysignals
    copying src/cysignals/signals.pxd -> build/lib.linux-x86_64-3.9/cysignals
    copying src/cysignals/pysignals.pxd -> build/lib.linux-x86_64-3.9/cysignals
    copying src/cysignals/memory.pxd -> build/lib.linux-x86_64-3.9/cysignals
    copying src/cysignals/cysignals_config.h -> build/lib.linux-x86_64-3.9/cysignals
    copying src/cysignals/pxi_warning.h -> build/lib.linux-x86_64-3.9/cysignals
    copying src/cysignals/macros.h -> build/lib.linux-x86_64-3.9/cysignals
    copying src/cysignals/struct_signals.h -> build/lib.linux-x86_64-3.9/cysignals
    running build_ext
    building 'cysignals.signals' extension
    creating build/temp.linux-x86_64-3.9
    creating build/temp.linux-x86_64-3.9/build
    creating build/temp.linux-x86_64-3.9/build/src
    creating build/temp.linux-x86_64-3.9/build/src/cysignals
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wno-unused -g -O2 -g -O2 -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -U_FORTIFY_SOURCE -Isrc/cysignals -Isrc -I/home/user/git/sage/local/include/python3.9 -c build/src/cysignals/signals.c -o build/temp.linux-x86_64-3.9/build/src/cysignals/signals.o -pthread
    In file included from build/src/cysignals/signals.c:1585:
    build/src/cysignals/implementation.c: In function ‘setup_trampoline’:
    build/src/cysignals/implementation.c:339:29: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘long int’ [-Wsign-compare]
      339 |     if (trampolinestacksize < PTHREAD_STACK_MIN)
          |                             ^
    In file included from build/src/cysignals/signals.c:1585:
    build/src/cysignals/implementation.c: In function ‘setup_alt_stack’:
    build/src/cysignals/implementation.c:448:17: error: storage size of ‘alt_stack’ isn’t constant
      448 |     static char alt_stack[MINSIGSTKSZ + 5120 + BACKTRACELEN * sizeof(void*)];
          |                 ^~~~~~~~~
    error: command '/usr/bin/gcc' failed with exit code 1
    ----------------------------------------
  Rolling back uninstall of cysignals
  Moving to /home/user/git/sage/local/bin/cysignals-CSI
   from /tmp/pip-uninstall-raru53z5/cysignals-CSI
  Moving to /home/user/git/sage/local/lib/python3.9/site-packages/cysignals-1.11.1.dist-info/
   from /home/user/git/sage/local/lib/python3.9/site-packages/~ysignals-1.11.1.dist-info
  Moving to /home/user/git/sage/local/lib/python3.9/site-packages/cysignals/
   from /home/user/git/sage/local/lib/python3.9/site-packages/~ysignals
  Moving to /home/user/git/sage/local/share/cysignals/
   from /home/user/git/sage/local/share/~ysignals
ERROR: Command errored out with exit status 1: /home/user/git/sage/local/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-b42k_wkp/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-b42k_wkp/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-m6wbav70/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/git/sage/local/include/python3.9/cysignals Check the logs for full command output.
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the '/home/user/git/sage/local/bin/python3 -m pip install --upgrade pip' command.
```

**Comment by kliem** [comment] 2021-12-02 09:31
This is a duplicate of #150, which has already been resolved.

https://trac.sagemath.org/ticket/32576 updates cysignals. It is a blocker ticket, so I'm rather confident it will be included soon and definitely in the next stable release.

**Comment by kliem** [comment] 2021-12-02 09:31
Feel free to reopen this issue, if https://trac.sagemath.org/ticket/32576 does not solve this for you.

**Closed by kliem** 2021-12-02 09:31 UTC
